version: '2.2' # Keep on old version because Travis only provides old docker-compose

# Reusable options
x-slides-base: &slides-base
  build: ./
  image: slides-builder
  environment:
      - PRESENTATION_URL=${PRESENTATION_URL}
  volumes:
      - ./content:/app/content
      - ./dist:/app/dist
      - ./assets:/app/assets
      - ./gulp/gulpfile.js:/app/gulpfile.js
      - ./gulp/tasks:/app/tasks
      - ./package.json:/app/package.json

services:
  serve:
    <<: *slides-base
    ports:
        - "8000:8000"

  build:
    <<: *slides-base
    command: "build"

  qrcode:
    <<: *slides-base
    entrypoint: /app/node_modules/.bin/qrcode
    command: -t png -o /app/dist/images/qrcode.png ${PRESENTATION_URL}
