
= Tester une CLI

== Problématique

* Je fournis une CLI avec un `README`
* Comment s'assurer que la documentation:
**  Est à jour ?
**  Est fonctionnelle ?

== Idée

* Test "E2E" pour jouer les scénarios écrits (ref. Asciidoctor)
* Jouer une command == automatiser du shell

== bats

[quote]
__
Bats is a TAP-compliant testing framework for Bash. It provides a simple way to verify that the UNIX programs you write behave as expected.
__

link:https://github.com/sstephenson/bats[bats on icon:github[]]

== Exemple

[source,bash]
----
#!/usr/bin/env bats
# Fichier "test-docker.bats"

@test "Binary docker is on the current PATH" {
  command -v docker
}

DOCKER_VERSION=18.09.3
@test "docker version is ${DOCKER_VERSION}" {
  docker -v | grep "${DOCKER_VERSION}"
}
----

== Execution

[source,bash]
----
$ bats test-docker.bats
 ✓ Binary docker is on the current PATH
 ✓ docker version is 18.09.3

2 tests, 0 failures
----

== TAP: Test Anything Protocol

* Bats permet d'exporter en format link:http://testanything.org/[TAP]
** Parsable par une machine
** Vient du monde Perl, mais beaucoup de modules: (exemple: link:https://wiki.jenkins.io/display/JENKINS/TAP+Plugin[Jenkins TAP module])

[source,bash]
----
bats --tap addition.bats
1..2
ok 1 Binary docker is on the current PATH
ok 2 docker version is 18.09.3
----

== Facilitées : run

* `run <COMMAND>` pour tester le exit code ou l'output

[source,bash]
----
@test "ls sur un fichier non existant a une erreur 1" {
  run ls -l /nonexistent_filename
  [ "$status" -eq 1 ]
  [ "$output" = "ls:/nonexistent_filename: No such file or directory
}
----

== Facilitées : load

* `load custom_helper` pour réutiliser du code

[source,bash]
----
#!/bin/bash
# fichier "custom_helper.bash"

say_hello() {
    echo "Hello"
}
----

[source,bash]
----
#!/bin/bats
load custom_helper

@test "Dire bonjour" {
    say_hello
}
----

== Facilitées : Hooks

* `setup()` et `teardown()` sont exécutés (respectivement) avant et après chaque test

[source,bash]
----
setup() {
    eval $(minikube env)
}
teardown() {
    unset DOCKER_HOST
}

@test "docker avec minikube" {
    # setup has been run
    docker ps # Using minikube
    # teardown will be run
}
----

== Facilitées : Variables


* `$BATS_TEST_FILENAME`
* `$BATS_TEST_DIRNAME`
* `$BATS_TEST_NAMES`
* `$BATS_TEST_NAME`
* `$BATS_TEST_DESCRIPTION`
* `$BATS_TEST_NUMBER`
* `$BATS_TMPDIR`
